[package]
name = "nativelink-util"
version = "0.3.0"
edition = "2021"

[dependencies]
nativelink-config = { path = "../nativelink-config" }
nativelink-error = { path = "../nativelink-error" }
nativelink-proto = { path = "../nativelink-proto" }

async-lock = "3.3.0"
async-trait = "0.1.80"
blake3 = { version = "1.5.1", features = ["mmap"] }
bytes = "1.6.0"
futures = "0.3.30"
hex = "0.4.3"
lru = "0.12.3"
parking_lot = "0.12.1"
pin-project-lite = "0.2.14"
prometheus-client = "0.22.2"
prost = "0.12.4"
prost-types = "0.12.4"
rand = "0.8.5"
serde = { version = "1.0.198", features = ["derive"] }
sha2 = "0.10.8"
tokio = { version = "1.37.0", features = [ "sync", "fs", "rt", "time", "io-util", "macros" ] }
tokio-stream = { version = "0.1.15", features = ["sync"] }
tokio-util = { version = "0.7.10" }
tonic = { version = "0.11.0", features = ["tls"] }
tracing = "0.1.40"

[dev-dependencies]
pretty_assertions = "1.4.0"
rand = "0.8.5"
mock_instant = "0.3.2"
