[package]
name = "nativelink-worker"
version = "0.3.0"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }
nativelink-proto = { path = "../nativelink-proto" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-store = { path = "../nativelink-store" }

# TODO(aaronmondal): This should not be a dependency. Move corresponding
#                    functionality out of the schedulers.
nativelink-scheduler = { path = "../nativelink-scheduler" }

async-lock = "3.3.0"
async-trait = "0.1.80"
bytes = "1.6.0"
filetime = "0.2.23"
formatx = "0.2.2"
futures = "0.3.30"
hex = "0.4.3"
parking_lot = "0.12.1"
prost = "0.12.4"
relative-path = "1.9.2"
scopeguard = "1.2.0"
serde = "1.0.198"
serde_json5 = "0.1.0"
shlex = "1.3.0"
tokio = { version = "1.37.0", features = ["sync", "rt", "process"] }
tokio-stream = { version = "0.1.15", features = ["fs"] }
tonic = { version = "0.11.0", features = ["gzip", "tls"] }
tracing = "0.1.40"
uuid = { version = "1.8.0", features = ["v4"] }

[dev-dependencies]
hyper = "1.3.1"
once_cell = "1.19.0"
pretty_assertions = "1.4.0"
prost-types = "0.12.4"
rand = "0.8.5"
