[package]
name = "nativelink-store"
version = "0.3.0"
edition = "2021"

[dependencies]
nativelink-error = { path = "../nativelink-error" }
nativelink-config = { path = "../nativelink-config" }
nativelink-util = { path = "../nativelink-util" }
nativelink-proto = { path = "../nativelink-proto" }

arc-cell = "0.3.3"
async-lock = "3.3.0"
async-trait = "0.1.80"
aws-config = "1.2.1"
aws-sdk-s3 = { version = "1.24.0" }
aws-smithy-runtime = { version = "1.3.1" }
bincode = "1.3.3"
blake3 = "1.5.1"
byteorder = "1.5.0"
bytes = "1.6.0"
filetime = "0.2.23"
futures = "0.3.30"
hex = "0.4.3"
http-body = "1.0.0"
hyper = { version = "1.3.1" }
hyper-rustls = { version = "0.24.2", features = ["webpki-tokio"] }
lz4_flex = "0.11.3"
parking_lot = "0.12.1"
prost = "0.12.4"
rand = "0.8.5"
redis = { version = "0.25.3", features = ["tokio-comp", "tokio-rustls-comp", "connection-manager"] }
serde = "1.0.198"
sha2 = "0.10.8"
shellexpand = "3.1.0"
tempfile = "3.10.1"
tokio = { version = "1.37.0" }
tokio-stream = { version = "0.1.15", features = ["fs"] }
tokio-util = { version = "0.7.10" }
tonic = { version = "0.11.0", features = ["gzip", "tls"] }
tracing = "0.1.40"
uuid = { version = "1.8.0", features = ["v4"] }

[dev-dependencies]
redis-test = { version = "0.4.0", features = ["aio"] }
pretty_assertions = "1.4.0"
memory-stats = "1.1.0"
once_cell = "1.19.0"
http = "1.1.0"
aws-smithy-types = "1.1.8"
aws-sdk-s3 = { version = "1.24.0"  }
aws-smithy-runtime = { version = "1.3.1", features = ["test-util"] }
aws-smithy-runtime-api = "1.4.0"
